volumes:
  mongodata:
    driver: local
  redisdata:
    driver: local

services:
  redis:
    image: redis:7.2
    container_name: facilitator-controller-redis
    ports:
      - ${REDIS_PORT-6379}:6379
    volumes:
      - redisdata:/data
    command: [ "redis-server" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  mongo:
    image: mongo:5.0
    container_name: facilitator-controller-mongo
    ports:
      - ${MONGO_PORT-27017}:27017
    volumes:
      - mongodata:/data/db
  facilitator-controller:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
